[package]
name = "gadget-service"
version = "0.1.0"
edition = "2021"

[dependencies]
fschema-lib = { workspace = true }
clap = { version = "4.0.26", features = ["derive"] }
nix = { version = "0.25.0", features = ["user"] }
