[package]
name = "bork"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lmk-hid = { path = "../lmk-hid" }
nom = "7"