[package]
name = "key-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
virt-hid = { workspace = true }
mcp23017-rpi-lib = { workspace = true }
configfs = { workspace = true }
key-module = { workspace = true }
tokio = { version = "1", features = ["full"] }
libc = "0.2"
serde = { version = "1.0", features = ["derive"]}
typetag = "0.2.3"
serde_json = "1.0"
slab = "0.4"
itertools = "0.10.5"
dirs = "4.0.0"
clap = { version = "4.0.29", features = ["derive"] }
midir = "0.8.0"
midi-msg = "0.4"
log = "0.4.17"
nanomsg = {version = "0.7.2"}
dynfmt = { version = "0.1.5"}
abi_stable = "0.11.1"
pyo3 = { version = "0.17.3",features = ["abi3-py39", "auto-initialize"]  }
log4rs = { version = "1.2.0", features = []}

[dependencies.uinput]
version = "0.1.3"
default-features = false
