[package]
name = "hid-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
configfs = { workspace = true }
virt-hid = { workspace = true }
libc = "0.2.138"
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }
