[package]
name = "bork"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug = []

[dependencies]
virt-hid = { workspace = true }
nom = "7"
clap = { version = "4.0.15", features = ["derive"] }